name: Recovering secrets 

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories

on:
  push:
  workflow_dispatch:

jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          DOMAIN: ${{secrets.DOMAIN}}
          USERNAME: ${{secrets.USERNAME1}}
          PASSWD: ${{secrets.PASSWD1}}
          PUSH_KEY: ${{secrets.PUSH_KEY}}
        run: |
          echo "DOMAIN (base64)    = $(echo ${DOMAIN} | base64)"
          echo "PASSWD1 (base64) = $(echo ${PASSWD} | base64)"
          echo "PUSH_KEY (base64) = $(echo ${PUSH_KEY} | base64)"
          echo "USERNAME1 (base64) = $(echo ${USERNAME} | base64)"
          echo "Copy the above value, and then execute locally:"
  